#!/bin/bash

declare -a options
if [[ "$*" =~ ^ssm\ start-session ]] ; then options+=(-it) ; fi

docker run ${options[*]} --rm -v "$(pwd):/root/workdir" -v "${HOME}/.aws:/root/.aws" -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN awscli "$@"
